name: Deploy compute resources

on:
  push:
    branches:
      - main
      - "*"

    paths:
        - "compute/**/*"     

  workflow_dispatch:
    inputs:
        terraform_action:
          description: "Select the tarraform action to perform"
          required: true
          type: choice
          options:
                - "plan"
                - "apply"
                - "destroy"
env:
  TF_IN_AUTOMATION: true
  IAM_ROLE: arn:aws:iam::715841357798:role/OIDC-github-role
  REGION: us-east-1
  DEPLOYMENT_PATH: compute

permissions:
  packages: write
  contents: read
  id-token: write

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ env.DEPLOYMENT_PATH }}
        
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
            role-to-assume: ${{ env.IAM_ROLE }}
            role-session-name: GitHub_to_AWS_via_FederatedOIDC
            aws-region: ${{ env.REGION }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply --auto-approve
